# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - cd server && npm install && cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build
  post_build:
    commands:
      - rm -rf server/public/static && cp dist/static -r server/public/static && rm server/views/client.html && cp dist/index.html server/views/client.html  
artifacts:
  secondary-artifacts:
    server:
      files:
        - '**/*'
      base-directory: server

    
